---
# Production environment override configured for Traefik routing
services:
  php:
    image: ${IMAGES_PREFIX:-}focusboard-api-prod
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      SERVER_NAME: "http://api.92.5.38.37.nip.io"
      CORS_ALLOW_ORIGIN: "^https?://(92\\.5\\.38\\.37\\.nip\\.io)$"

    ports: !reset []

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focusboard-api.rule=Host(`api.92.5.38.37.nip.io`)"
      - "traefik.http.routers.focusboard-api.entrypoints=web"
      - "traefik.http.services.focusboard-api.loadbalancer.server.port=80"

    networks:
      - web_proxy
      - default

  database:
    ports: !reset []

networks:
  web_proxy:
    external: true
